# You always need to specify the starting condition for your image, which sets the stage for
# all actions you will take to get your container runtime setup. Here we are specifying we
# want the starting condition to be a linux distro with node without the extra software normally
# included for general computer use. This is a striped down runtime environment
FROM node:lts

# After you set your starting condition you need to tell docker what files to copy into the
# image environment, which we can then use in our container. Here we keep it simple and just
# pass the already created index.js into the image environment renamed as "app.js"
COPY ./dist/index.js app.js

# Once you have everything ready to be run you use ENTRYPOINT to specify the command you want run
# when a container is created from the image associated with this dockerfile
ENTRYPOINT [ "node", "app.js" ]

# When building an image make sure to include a tag and a reference to the location of
# the dockerfile. Use `-t` and then a tag name to give the image a name, and then reference the
# location of the dockerfile relative to the working directory (. if it is in the same location)