services:
  jenkins-controller:
    image: jenkins/jenkins:lts-jdk21
    container_name: jenkins-controller
    privileged: true
    user: root
    ports:
      - "8080:8080"   # Web UI
      - "50000:50000" # Agent communication
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-net
    restart: always

  jenkins-agent:
    image: jenkins/agent:jdk21
    container_name: jenkins-agent
    privileged: true
    user: root
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=PASTE_YOUR_PUBLIC_KEY_HERE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-net
    restart: always

networks:
  jenkins-net:
    driver: bridge

volumes:
  jenkins_data: