spring.application.name=demo
# By default, your application listens to host 127.0.0.1
# In order to allow for outside requests to even reach your server you need to
# change the server address property to 0.0.0.0
server.address=0.0.0.0
