package com.example.demo.entity;

import java.util.UUID;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;
import lombok.NoArgsConstructor;

/*
    This User class is going to be my User entity: whenever  user data is utilized in my application this class
    will be used to represent it. We need to make sure that all relevant data for our users is present  to
    start. At a minimum we need a username and password field to represent the actual username and password
    the user creates. Thinking ahead, usernames tend to be unique so we could have the username act as our
    primary key if we did not want to make a unique field for the id.
*/
@Data // tells Lombok to provide setters, getters, required args constructor, and more
@NoArgsConstructor // needed for Entity decorator
@Entity // indicates the class should be mapped to a table in our database
@Table(name = "users") // if you want to change the name of your table specify it in the decorator
public class User {
    @Column // indicates the field represents a column
    @Id // indicates the field is the primary key (column is technically not needed when we use this)
    @GeneratedValue(strategy = GenerationType.UUID) // indicates the value should be generated by the db
    private UUID id;
    @Column(nullable = false, unique = true) // tells Spring to make the username column unique and not nullable
    private String username;
    @Column(nullable = false) // tells Spring to make the password not nullable
    private String password;
}
